[package]
name = "airs"
license = "MIT"
version = "0.1.0"
description = "Algorithm in Rust"
authors = ["aQua <hi@aQuaYi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
